### ISSUE TITLE
reproducing results for humanoid run

### ISSUE THREAD

**Issue by snailrowen1337** [facebookresearch/drqv2#1]
Thanks for open sourcing this! I wanted to replicate the results on the humanoid run/stand task. Using the default parameter I'm able to get similar result on the walker stand task, i.e. ~400 reward after 15 million stems. However, for the walker run task no learning seems to happen, see attached figure which is averaged across 5 runs. The only change I've made to the parameters is setting ```stddev_schedule: 'linear(1.0,0.1,2000000)```. Are there any other modifications necessary for the humanoid run task? Thanks!!

<img width="500" alt="perf" src="https://user-images.githubusercontent.com/45402632/128637351-0bdbc399-d5da-4633-92be-0765d8ee4f11.png">

**Comment by denisyarats** [comment]
I'm confused, are you trying to replicate humanoid or walker tasks?

For humanoid tasks you also need to change learning rate to `8e-5` and set `feature_dim` to `100` together with `stddev_schedule: 'linear(1.0,0.1,2000000)`.

**Comment by snailrowen1337** [comment]
I'm trying to replicate the humanoid tasks. Got it, Appendix B says "Humanoid Stand/Walk We set learning rate to 8 × 10−5 and increase features dim. to 100." -- so I assumed that humanoid run would learning rate of 1e-4. This must be the issue then, thanks!

**Comment by denisyarats** [comment]
Yeah, this is a typo, it should say Stand/Walk/Run. I will fix it.

**Comment by slerman12** [comment]
I noticed that the runs vary a little from run to run despite the random seed being set. Is this expected? I'm testing quadruped_walk with default settings.
