### ISSUE TITLE
Truncation for exploration?

### ISSUE THREAD

**Issue by AaronLiu1997** [facebookresearch/drqv2#13]
I'm reading the paper and code, and can't follow the truncation process. Table 2 sets exploration stddev. clip equal to 0.3, so I assume that the exploration noise is clipped. However, the action seems to be selected by ```action = dist.sample(clip=None)``` which does no clipping. Instead clipping is seemingly applied during training with ```dist.sample(clip=self.stddev_clip)```. Am I misunderstanding something here? Thanks!!

**Comment by denisyarats** [comment]
This is correct, the exploration noise is only being clipped when the sampled action is being used to query the Q function.

**Comment by AaronLiu1997** [comment]
Got it, thanks! I guess I was just confused about the terminology then!
