### ISSUE TITLE
Evaluation video overwritten

### ISSUE THREAD

**Issue by medric49** [facebookresearch/drqv2#14]
I have noticed, in this [line](https://github.com/facebookresearch/drqv2/blob/21e9048bf59e15f1018b49b850f727ed7b1e210d/train.py#L116) when you are saving evaluation episodes, that you are actually overwriting previous evaluation videos of the same global frame when `num_eval_episodes > 1`.

```
            self.video_recorder.save(f'{self.global_frame}.mp4')
``` 
The attribute `self.global_frame`  doesn't change during the `self.cfg.num_eval_episodes` evaluations in the loop.

I would propose this line instead
```
            self.video_recorder.save(f'{self.global_frame}_{episode}.mp4')
```
or other things like that.

**Comment by medric49** [comment]
Finally, I understood what you did with this line
```
            self.video_recorder.init(self.eval_env, enabled=(episode == 0))
```
You record only the first evaluation episode.

Is there any reason?

**Comment by denisyarats** [comment]
Hi, there is no overwrite, since only the first episode is being recorded. If you need to save videos for more episodes you can change it locally.
