### ISSUE TITLE
One more question, sorry...

### ISSUE THREAD

**Issue by slerman12** [facebookresearch/drqv2#18]
Hi, is the random augmentation implemented a faster/better transform than the torchvision `transforms.RandomAffine` function?

**Comment by denisyarats** [comment]
`RandomAffine` doesn't allow different shifts for individual samples in the batch, which is crucial.

**Comment by slerman12** [comment]
Can I ask, what if the RandomAffine was applied in the DataLoader?

**Comment by slerman12** [comment]
Sorry, I gotta bump this. I think for different augmentations, this could be a big speedup, especially if applying each one uniquely per datapoint is crucial
