### ISSUE TITLE
custom env

### ISSUE THREAD

**Issue by ss555** [facebookresearch/drqv2#19]
Hello I would like to train your algorithm on the fish task of the dm_control_suite, however, it's not in the list, could you please tell me where to start. I also have a custom visual env based on pyglet, what steps should I take to couple it with ur algorithm.
Thanks in advance!

**Comment by denisyarats** [comment]
You should be able to just invoke the fish task directly, since it is part of the standard DMC suite.
I'm not familiar with pyglet and unable to provide you with any advice.
