### ISSUE TITLE
Redundant n-step trick in this repo?

### ISSUE THREAD

**Issue by emigmo** [facebookresearch/drqv2#5]
Hi, 

There are two places in this code base that use **n-step returns** trick for TD error.
1. https://github.com/facebookresearch/drqv2/blob/ccb9a4d373d559fa3c3460784279d7c72e46c58a/dmc.py#L40
2. https://github.com/facebookresearch/drqv2/blob/ccb9a4d373d559fa3c3460784279d7c72e46c58a/replay_buffer.py#L156

For the first place, num_repeats=2, in the ActionRepeatWrapper of env wrapper _dmc_.
For the second place, _nstep=3, in the replay_buffer.
And both of them are used the discount reward instead of the original reward.

I think it is inconsistent with the parameters described in the paper.

**Comment by denisyarats** [comment]
The discount inside `dmc.py` is the MDP discount rather than the agent discount. This discount is set to `1.0`, while the agent discount, specified in the config file, is set to `0.99`. So there is no inconsistency

**Comment by denisyarats** [comment]
``
