### ISSUE TITLE
Great work! Exploration noise question...

### ISSUE THREAD

**Issue by slerman12** [facebookresearch/drqv2#6]
Great work! Jus ta question about exploration noise. Is there a benefit/reason for using exploration noise over a stochastic policy with a learned mean and standard variation?

**Comment by denisyarats** [comment]
Hi,  we learn mean for the policy but keep std fixed, so the policy is still stochastic.  The advantage of doing so is that learning std sometimes might lead to premature policy collapse, which prevents exploration in harder environments.

**Comment by slerman12** [comment]
Okay thanks, that makes sense. But, wouldn't entropy account for this?
